- name: disabled selinux
  selinux:
   state: disabled
  when: ansible_selinux['status'] == 'enabled' and ansible_selinux['config_mode'] != 'disabled'

- name: Install Zabbix Repo
  yum:
    name: https://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm
    state: present

- firewalld:
    service: http
    permanent: true
    immediate: yes
    state: enabled
